### ISSUE TITLE
Page changing on Refresh 

### ISSUE THREAD

**Issue by deepakpotluri** [Limitless-Global-Technologies/app.productstreak#32]
If we try to refresh the page then the widget key is 66eab4f3dac5ecf475ec65ee for every widget then after 1 or 2 seconds the widget key is updating to unique
Also after refresh one default page is appearing and getting the actual page after a second delay
This is after a refresh
![Screenshot 2024-09-19 122741](https://github.com/user-attachments/assets/cbf0fb74-551c-4304-9144-1a6c3996e979)
This is unique widget key after 2seconds
![Screenshot 2024-09-19 123004](https://github.com/user-attachments/assets/5b5970e7-dfb1-437b-bc7e-2d509d93a688)

**Comment by akash-limitlessglobaltechnologies** [comment]
issue resolved!!!!
